export const UPDATE_APP_LOADING_STATUS = "UPDATE_APP_LOADING_STATUS";
export const UPDATE_LOCALE = "UPDATE_LOCALE";
export const UPDATE_LOGIN = "UPDATE_LOGIN";
export const UPDATE_LOADING = "UPDATE_LOADING";
