export const UPDATE_USER_ADDRESSES = "UPDATE_USER_ADDRESSES";
export const UPDATE_USER_BILLING_ADDRESSES = "UPDATE_USER_BILLING_ADDRESSES";
export const UPDATE_USER_SHIPPING_ADDRESSES = "UPDATE_USER_SHIPPING_ADDRESSES";
export const UPDATE_USER_ORDERS = "UPDATE_USER_ORDERS";
