export const UPDATE_CITY_ID = "UPDATE_CITY_ID";
export const UPDATE_WAREHOUSE_ID = "UPDATE_WAREHOUSE_ID";
export const UPDATE_QUOTE_ID = "UPDATE_QUOTE_ID";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_ID = "UPDATE_CUSTOMER_ID";
