export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_SEND_DATA = "UPDATE_SEND_DATA";
export const UPDATE_VERIFY_DATA = "UPDATE_VERIFY_DATA";
export const UPDATE_CUSTOMER_DATA = "UPDATE_CUSTOMER_DATA";
export const UPDATE_CUSTOMER_BILLING = "UPDATE_CUSTOMER_BILLING";
export const UPDATE_CUSTOMER_SHIPPING = "UPDATE_CUSTOMER_SHIPPING";
